---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks: 
    - name: Install Apache
      yum: name={{ item }} state=present
      with_items:
      - httpd
      - php
      - php-mysql
    - name: Download WordPress
      get_url: url=http://wordpress.org/wordpress-latest.tar.gz dest=/var/www/html/wordpress.tar.gz
    - name: Extract WP
      command: "tar xzf /var/www/html/wordpress.tar.gz -C /var/www/html --strip-components 1"
    - name: Make directory tree readable
      file:
         path: /var/www/html
         mode: u=rwx,g=rx,o=rx
         recurse: yes
         owner: apache
         group: apache
    - name: Ensure the apache is started
      service: name=httpd state=started enabled=yes 
